apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-example-nginx-config
  namespace: codeweek
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        auth_basic "secret";
        auth_basic_user_file /secrets/htpasswd;
    }
