apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: codeweek
spec:
  selector:
    matchLabels:
      app: test-deployment
  replicas: 10
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - name: testcontainer
          image: traefik/whoami
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: WHOAMI_NAME
              value: "hello k8s"
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
