apiVersion: v1
kind: Service
metadata:
  name: testservice
  namespace: codeweek
spec:
  selector:
    app: test-deployment
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
