apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  namespace: codeweek
spec:
  containers:
    - name: testcontainer
      image: traefik/whoami
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      env:
        - name: WHOAMI_NAME
          value: "hello world"
      ports:
        - containerPort: 80
          name: http
      readinessProbe:
        httpGet:
          port: 80
      livenessProbe:
        tcpSocket:
          port: 80
