apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: codeweek
spec:
  containers:
    - name: testcontainer
      image: hello-world
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
