apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replica-set
  namespace: codeweek
spec:
  selector:
    matchLabels:
      app: testpod
  replicas: 2
  template:
    metadata:
      labels:
        app: testpod
    spec:
      containers:
        - name: testcontainer
          image: traefik/whoami
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: WHOAMI_NAME
              value: some_value
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
